name: Check sources
on:
  push:
    branches:
      - 'main'
jobs:
   container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-action
        with:
          docker_repo: trialk033s3.jfrog.io/docker-trial
          docker_user: fouzia.merain@gmail.com
          docker_token: ${{ secrets.JFROG_DOCKER_TOKEN }}
