name: Check sources
on: push
jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  tests:
    needs: testscript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make tests
  Docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - run: make doc
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Docker:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: user/app:latest
